spring:
  data:
    mongodb:
      uri: mongodb://letcafe:19941231@letcafe.cn:27017/LiveSpider
  redis:
    host: letcafe.cn
    port: 8479
    password: redisServer
huya:
  CHROME_DRIVER_LOCATION: /home/tank/chrome/chromedriver
  SYSTEM_IS_OPEN_GUI: false