spring:
  data:
    mongodb:
      uri: mongodb://username:password@ip:port/db
  redis:
    host: ip
    port: 6379
    password: password
huya:
  CHROME_DRIVER_LOCATION: chromedriverLocation
  SYSTEM_IS_OPEN_GUI: false