spring:
  datasource:
    url: jdbc:mysql://letcafe.cn:3306/live_spider?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&character_set_server=utf8mb4&&characterEncoding=utf-8
    username: dongyuguo
    password: Gg@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 6
      min-idle: 4
      initial-size: 10
      default-auto-commit: true
  data:
    mongodb:
      uri: mongodb://letcafe:19941231@letcafe.cn:27017/LiveSpider
  redis:
    host: letcafe.cn
    port: 8479
    password: redisServer