spring:
  profiles:
#    active: dev
    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: gdycn@qq.com
    password: etictvelkfbwbicf
    default-encoding: UTF-8
server:
  port: 8080
  servlet:
    context-path: /LiveSpider
logging:
  config: classpath:log4j2.xml
huya:
  YY_ID: 1656777876
  PASSWORD: gdy19941231
  COOKIE_IN_REDIS: loginCookie_1656777876