spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/live_spider?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&character_set_server=utf8mb4&&characterEncoding=utf-8
    username: root
    password: 123456
  data:
    mongodb:
      database: LiveSpider
      host: localhost
      port: 27017
  redis:
    host: localhost
    port: 6379
    password: redisServer
