spring:
  profiles:
    # 选择启动哪一个配置类下的文件
    active: dev
#    active: prod
  datasource:
    hikari:
      maximum-pool-size: 10
      auto-commit: true
      minimum-idle: 2
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: gdycn@qq.com
    password: etictvelkfbwbicf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
server:
  port: 8080
  servlet:
    context-path: /LiveSpider
logging:
  config: classpath:log4j2.xml
# 暴露所有管理相关的信息
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /system
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

